version: '3.8'
services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5000:5000'

volumes:
  postgres: